### ISSUE TITLE
Bug when 'm' first

### ISSUE THREAD

**Issue by OhmPopy** [NearTox/SVGtoSkPath#1]
Convert string 
"m28.5 16.92l.14-.8.65.47a9.8 9.8 0 0 1 1.87 2A10.12 10.12 0 0 1 33 24.5C33 30.28 28.28 35 22.5 35S12 30.28 12 24.5c0-4.4 1.71-6.67 6.46-10.3l.49-.36a30 30 0 0 0 3.2-2.7l.4-.39.34.44a12.57 12.57 0 0 1 1.05 1.64 7.95 7.95 0 0 1 .93 5.5 28.56 28.56 0 0 1-.71 3.64c2.46-.27 3.85-2.04 4.35-5.05zm-8.95-2.29l-.48.37C14.55 18.45 13 20.5 13 24.5c0 5.22 4.28 9.5 9.5 9.5s9.5-4.28 9.5-9.5c0-2.08-.62-3.86-1.66-5.34a8.91 8.91 0 0 0-1.02-1.22C28.55 21.13 26.66 23 23.5 23h-.66l.18-.64a35.38 35.38 0 0 0 .49-2.02c.16-.74.28-1.46.37-2.14a7 7 0 0 0-.82-4.9c-.2-.38-.41-.72-.63-1.04-.74.7-1.55 1.36-2.88 2.37z"

to:

SkPath p;
 p.setFillType(SkPath::kWinding_FillType);
p.moveTo(-107374144.000000, -107374160.000000);
p.lineTo(-107374144.000000, -107374160.000000);
p.lineTo(-107374144.000000, -107374160.000000);
p.arcTo(SkPoint::Make(9.800000, 9.800000), 0.000000, (SkPath::ArcSize) SkToBool(0.000000), (SkPath::Direction) !SkToBool(1.000000),SkPoint::Make(-107374144.000000, -107374160.000000));
p.arcTo(SkPoint::Make(10.120000, 10.120000), 0.000000, (SkPath::ArcSize) SkToBool(0.000000), (SkPath::Direction) !SkToBool(1.000000),SkPoint::Make(33.000000, 24.500000));
p.cubicTo(33.000000, 30.280001, 28.280001, 35.000000, 22.500000, 35.000000);
p.cubicTo(16.719999, 35.000000, 12.000000, 30.280001, 12.000000, 24.500000);
p.cubicTo(12.000000, 20.100000, 13.710000, 17.830000, 18.459999, 14.200000);
p.lineTo(18.949999, 13.840000);
p.arcTo(SkPoint::Make(30.000000, 30.000000), 0.000000, (SkPath::ArcSize) SkToBool(0.000000), (SkPath::Direction) !SkToBool(0.000000),SkPoint::Make(22.150000, 11.140000));
p.lineTo(22.549999, 10.750000);
p.lineTo(22.889999, 11.190000);
p.arcTo(SkPoint::Make(12.570000, 12.570000), 0.000000, (SkPath::ArcSize) SkToBool(0.000000), (SkPath::Direction) !SkToBool(1.000000),SkPoint::Make(23.939999, 12.830000));
p.arcTo(SkPoint::Make(7.950000, 7.950000), 0.000000, (SkPath::ArcSize) SkToBool(0.000000), (SkPath::Direction) !SkToBool(1.000000),SkPoint::Make(24.869999, 18.330000));
p.arcTo(SkPoint::Make(28.559999, 28.559999), 0.000000, (SkPath::ArcSize) SkToBool(0.000000), (SkPath::Direction) !SkToBool(1.000000),SkPoint::Make(24.160000, 21.969999));
p.cubicTo(26.619999, 21.699999, 28.010000, 19.930000, 28.510000, 16.919998);
p.close();
p.moveTo(-107374152.000000, -107374160.000000);
p.lineTo(-107374152.000000, -107374160.000000);
p.cubicTo(14.550000, 18.450001, 13.000000, 20.500000, 13.000000, 24.500000);
p.cubicTo(13.000000, 29.719999, 17.280001, 34.000000, 22.500000, 34.000000);
p.cubicTo(27.719999, 34.000000, 32.000000, 29.719999, 32.000000, 24.500000);
p.cubicTo(32.000000, 22.420000, 31.379999, 20.639999, 30.340000, 19.160000);
p.arcTo(SkPoint::Make(8.910000, 8.910000), 0.000000, (SkPath::ArcSize) SkToBool(0.000000), (SkPath::Direction) !SkToBool(0.000000),SkPoint::Make(29.320000, 17.940001));
p.cubicTo(28.549999, 21.129999, 26.660000, 23.000000, 23.500000, 23.000000);
p.lineTo(22.840000, 23.000000);
p.lineTo(23.020000, 22.360001);
p.arcTo(SkPoint::Make(35.380001, 35.380001), 0.000000, (SkPath::ArcSize) SkToBool(0.000000), (SkPath::Direction) !SkToBool(0.000000),SkPoint::Make(23.510000, 20.340000));
p.cubicTo(23.670000, 19.600000, 23.790001, 18.880001, 23.880001, 18.200001);
p.arcTo(SkPoint::Make(7.000000, 7.000000), 0.000000, (SkPath::ArcSize) SkToBool(0.000000), (SkPath::Direction) !SkToBool(0.000000),SkPoint::Make(23.060001, 13.300001));
p.cubicTo(22.860001, 12.920001, 22.650002, 12.580001, 22.430002, 12.260001);
p.cubicTo(21.690002, 12.960001, 20.880003, 13.620001, 19.550003, 14.630001);
p.close();

If 'M' is first token then not error.

**Comment by OhmPopy** [comment]
I build in vs 2012 so remove field in struct  SkPoint. 
fix:
	SkPoint()
	{
		fX = 0;
		fY = 0;
	}

**Comment by NearTox** [comment]
Thanks for report the issue,
I currently use C++17 and VS 2017 so I didn't notice that bug in C++0x

https://en.cppreference.com/w/cpp/compiler_support
